[package]
name = "image-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
libvips = "1.4.3"
dotenv = "0.15.0"
aws-config = "0.15.0"
aws-sdk-s3 = "0.15.0"
anyhow = "1.0"