name: build-images

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the docker images"
        required: true
        default: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_ACTOR }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build image from Dockerfile.builder
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.builder
          push: true
          tags: ghcr.io/chroniclehq/huffman-builder:${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build image from Dockerfile.runtime
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.runtime
          push: true
          tags: ghcr.io/chroniclehq/huffman-runtime:${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
