name: build

on:
  push:
    branches:
      - "master"

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      builder_changed: ${{ steps.check_builder.outputs.builder_changed }}
      runtime_changed: ${{ steps.check_runtime.outputs.runtime_changed }}
    steps:
      - uses: actions/checkout@v3

      - name: Run step when builder changes
        id: check_builder
        if: contains(steps.changed-files.outputs.modified_files, 'Dockerfile.builder')
        run: echo "::set-output name=builder_changed::True"

      - name: Run step when runtime changes
        id: check_runtime
        if: contains(steps.changed-files.outputs.modified_files, 'Dockerfile.runtime')
        run: echo "::set-output name=runtime_changed::True"

  build-builder:
    needs: [check-files]
    if: needs.check-files.outputs.builder_changed == 'True'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_ACTOR }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build image from Dockerfile.builder
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.builder
          push: true
          tags: ghcr.io/chroniclehq/huffman-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-runtime:
    needs: [check-files]
    if: needs.check-files.outputs.builder_changed == 'True'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_ACTOR }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build image from Dockerfile.runtime
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.runtime
          push: true
          tags: ghcr.io/chroniclehq/huffman-runtime:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-app:
    needs: [build-builder, build-runtime]
    if: ${{ !failure() }} # Check if the previous stages were successfull or skipped
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_ACTOR }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build image from Dockerfile.app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.app
          push: true
          tags: ghcr.io/chroniclehq/huffman-app:${{ github.sha }},ghcr.io/chroniclehq/huffman-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-ecs:
    needs: [build-app]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ap-south-1

      - name: Update ECS to force deployment with latest image
        run: aws ecs update-service --cluster ${{ secrets.AWS_ECS_CLUSTER }} --service ${{ secrets.AWS_ECS_SERVICE }} --force-new-deployment
