name: build

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_ACTOR }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.build
          push: true
          tags: ghcr.io/chroniclehq/huffman-build:0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker Runtime
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.runtime
          push: true
          tags: ghcr.io/chroniclehq/huffman-runtime:0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
