name: build-app

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_ACTOR }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build image from Dockerfile.app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.app
          push: true
          tags: ghcr.io/chroniclehq/huffman-app:0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
